### ISSUE TITLE
router.getParameters doesn't work for some functions

### ISSUE THREAD

**Issue by moraneva** [SpartanLabs/mindless#26]
The current mechanism for getting parameters off of a function uses the following line to get the arguments:
```js
let args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
```
However, I came across a scenario in my app where the `func.toString()` returned the following:
```js
get(request) {
        return __awaiter(this, void 0, void 0, function* () {
            let appId = request.get('appId');
            let limit = request.get('limit');
....
```
The current regex cannot map to this since it is prepending with `function `. We should allow it to just match by the first set of params:
```js
let args = func.toString().match(/\(([^)]*)\)/)[1];
```

**Comment by zRosenthal** [comment]
Should be fine unless someone decides to nest a comment with `(` or `)` in there function signature...
```ts
f(/*why would any one do this ()*/ a: string) {
  // do something
}
```

**Comment by zRosenthal** [comment]
I would still like to find better way to do this maybe with reflection or something but for  now its the best we got

**Comment by moraneva** [comment]
Yep, maybe look at what other big projects do for this
