### ISSUE TITLE
Need a way to easily grab optional parameters

### ISSUE THREAD

**Issue by moraneva** [SpartanLabs/mindless#30]
Right now, there is no way to easily get optional query parameters from a request without an exception being thrown. Ex:
```js
public async get(request: Request): Promise<Response> {
        let appId = request.get('appId');
...
```
For example, if `appId` was an optional parameter in the request above and was not included in the url this would throw an error. To handle this you would have to do something like the following:
```js
let appId;
try{
  appId = request.get('appId');
}
catch(error){
  appId = null;
}
```
Or some similar logic.

There should be an easy way of getting optional parameters. Something like this:
```js
let appId = request.get('appId'); // appId === undefined
// or
let appId = request.getOptionalParam('appId'); // appId == undefined
// or
let appId = request.get('appId', failOnMissing: false); //appId === undefined
```

**Comment by moraneva** [comment]
@zRosenthal liking the last option the best, lmk what you think

**Comment by zRosenthal** [comment]
Ya I dont see why you should have to access optional params any different than you would if they wernt optional... I also think optional params are a bad design choice but, to each their own, that being said what is the functionality of `failOnMissing: true` and `failOnMissing: false`? Does true throw an error? if so it should be errorOnMissing or `request.getOrError(key)`. and if is false does it just return undefined ?

**Comment by zRosenthal** [comment]
Im going to upvote my own suggestion on `request.getOrError(key)` rather than using the optional parameter `failOnMissing`. I think its clearer and cleaner.

**Comment by moraneva** [comment]
So have a `request.get(key)` and a `request.getOrError(key)`?

**Comment by moraneva** [comment]
I'll let you pick this back up when you get back :)
