### ISSUE TITLE
Remove path parameters from the event/request objects

### ISSUE THREAD

**Issue by moraneva** [SpartanLabs/mindless#54]
We are currently handling path parameters in two places ( in the `Request` class and also in the `Router`). We should totally remove the handling of path parameters in the `Request` class since the `Router` uses the route defined by the user. 

- We should create a data structure in `Request` that is dedicated to items that get added to the request through the `add` function.
- Query string parameters should also be given the lowest precedence

**Comment by zRosenthal** [comment]
addressed in #55
