### ISSUE TITLE
Ability to map fields in the request to partition/range keys for dynamo

### ISSUE THREAD

**Issue by moraneva** [SpartanLabs/mindless#64]
Users should be able to set up their table partition/hashKeys to accept fields from the income request.

For example,

If I were to set up a user table with partition scheme of "{name}:{email}", mindless should be able to map the `name` and `email` fields from a request to the partition key.

The following request
```
{
    "name": "Evan",
    "email": "evan@gmail.com"
}

```

would then use "Evan:evan@gmail.com" as the partition key value for dynamo access

**Comment by zRosenthal** [comment]
@moraneva  I think we should just remove the model facotry/data layer all together. Lets keep this package as a slim routing layer sort of as an alternative to express
